import { DesiredOutputPrecision } from '../../../Common/DataModel/DataSetAttributes';
import vtkImplicitFunction from '../../../Common/DataModel/ImplicitFunction';
import vtkIncrementalPointLocator from '../../../Common/DataModel/IncrementalPointLocator';
import vtkPolyData from '../../../Common/DataModel/PolyData';
import { vtkAlgorithm, vtkObject } from '../../../interfaces';

export interface IClipPolyDataInitialValues {
  clipFunction?: vtkImplicitFunction;
  insideOut?: boolean;
  value?: number;
  generateClipScalars?: boolean;
  generateClippedOutput?: boolean;
  outputPointsPrecision?: DesiredOutputPrecision;
  locator?: vtkIncrementalPointLocator;
}

type vtkClipPolyDataBase = vtkObject & vtkAlgorithm;

export interface vtkClipPolyData extends vtkClipPolyDataBase {
  /**
   * Create default locator. Used to create one when none is specified.
   * The locator is used to merge coincident points.
   */
  createDefaultLocator(): void;

  /**
   * Get the implicit function used to perform the clipping.
   */
  getClipFunction(): vtkImplicitFunction;

  /**
   * Get the output of the filter that contains the clipped pieces. (The output of the filter is the part that is not clipped.)
   * This output is only generated if the GenerateClippedOutput flag is on.
   */
  getClippedOutput(): vtkPolyData;

  /**
   * Get the flag that controls whether or not to generate scalars on the clipped output.
   * If this flag is off, then no scalars are generated on the clipped output.
   * If this flag is on, then scalars are generated on the clipped output.
   * The scalars are generated by evaluating the implicit function at the points of the clipped output.
   * The default is off.
   */
  getGenerateClippedOutput(): boolean;

  /**
   * Get the flag that controls whether or not to generate scalars on the output.
   * If this flag is off, then no scalars are generated on the output.
   * If this flag is on, then scalars are generated on the output.
   * The scalars are generated by evaluating the implicit function at the points of the output.
   * The default is off.
   */
  getGenerateClipScalars(): boolean;

  /**
   * Get the flag that controls whether or not to reverse the sense of what is inside and what is outside.
   * If this flag is off, then the implicit function is evaluated as is.
   * If this flag is on, then the implicit function is evaluated as if it were multiplied by -1. In other words, what is inside becomes outside and what is outside becomes inside.
   * The default is off.
   */
  getInsideOut(): boolean;

  /**
   * Get the locator used to merge coincident points.
   * By default, an instance of vtkMergePoints is used. (@see createDefaultLocator() method.)
   * To use a different locator, set it with the SetLocator() method.
   * To turn off merging of coincident points, set the locator to null.
   */
  getLocator(): vtkIncrementalPointLocator;

  /**
   * Get the output points precision.
   */
  getOutputPointsPrecision(): DesiredOutputPrecision;

  /**
   * Get the value used to perform clipping when not using an implicit function. The default is 0.0.
   */
  getValue(): number;

  /**
   *
   * @param inData
   * @param outData
   */
  requestData(inData: any, outData: any): void;

  /**
   * Set the implicit function used to perform the clipping.
   * @param clipFunction
   */
  setClipFunction(clipFunction: vtkImplicitFunction): boolean;

  /**
   * Set the flag that controls whether or not to generate scalars on the clipped output.
   * @param generateClippedOutput
   */
  setGenerateClippedOutput(generateClippedOutput: boolean): boolean;

  /**
   * Set the flag that controls whether or not to generate scalars on the output.
   * @param generateClipScalars
   */
  setGenerateClipScalars(generateClipScalars: boolean): boolean;

  /**
   * Set the flag that controls whether or not to reverse the sense of what is inside and what is outside.
   * @param insideOut
   */
  setInsideOut(insideOut: boolean): boolean;

  /**
   * Set the locator used to merge coincident points.
   * By default, an instance of vtkMergePoints is used. (@see createDefaultLocator() method.)
   * To use a different locator, set it with this method.
   * To turn off merging of coincident points, set the locator to null.
   *
   * @param locator The locator to use for merging coincident points.
   * @returns {Boolean} True if the locator was set successfully, false otherwise.
   */
  setLocator(locator: vtkIncrementalPointLocator): boolean;

  /**
   * Set the desired precision for the output types.
   * @param outputPointsPrecision
   */
  setOutputPointsPrecision(
    outputPointsPrecision: DesiredOutputPrecision
  ): boolean;
  setValue(value: number): boolean;
}

export function extend(
  publicAPI: object,
  model: object,
  initialValues?: IClipPolyDataInitialValues
): void;

export function newInstance(
  initialValues?: IClipPolyDataInitialValues
): vtkClipPolyData;

export declare const vtkClipPolyData: {
  newInstance: typeof newInstance;
  extend: typeof extend;
};

/**
 * vtkClipPolyData is a filter that clips polygonal data using either any subclass of vtkImplicitFunction, or the input scalar data.
 * Clipping means that it actually "cuts" through the cells of the dataset, returning everything inside of the specified implicit function (or greater than the scalar value) including "pieces" of a cell.
 * The output of this filter is polygonal data.
 *
 * To use this filter, you must decide if you will be clipping with an implicit function, or whether you will be using the input scalar data.
 * If you want to clip with an implicit function, you must:
 *
 * 1 - define an implicit function
 * 2 - set it with the SetClipFunction method
 * 3 - apply the GenerateClipScalarsOn method If a ClipFunction is not specified, or GenerateClipScalars is off (the default), then the input's scalar data will be used to clip the polydata.
 */
export default vtkClipPolyData;
