// This file is auto-generated by generate-gallery.mjs
export default [
  {
    "title": "ImplicitBoolean",
    "category": "Common",
    "image": "gallery/ImplicitBoolean.jpg",
    "link": "ImplicitBoolean.html"
  },
  {
    "title": "PointLocator",
    "category": "Common",
    "image": "gallery/PointLocator.jpg",
    "link": "PointLocator.html"
  },
  {
    "title": "Sphere",
    "category": "Common",
    "image": "gallery/Sphere.jpg",
    "link": "Sphere.html"
  },
  {
    "title": "TriangleStrip",
    "category": "Common",
    "image": "gallery/TriangleStrip.png",
    "link": "TriangleStrip.html"
  },
  {
    "title": "ClipPolyData",
    "category": "Filters",
    "image": "gallery/ClipPolyData.jpg",
    "link": "ClipPolyData.html"
  },
  {
    "title": "Cutter",
    "category": "Filters",
    "image": "gallery/Cutter.jpg",
    "link": "Cutter.html"
  },
  {
    "title": "CleanPolyData",
    "category": "Filters",
    "image": "gallery/CleanPolyData.jpg",
    "link": "CleanPolyData.html"
  },
  {
    "title": "PolyDataNormals",
    "category": "Filters",
    "image": "gallery/PolyDataNormals.jpg",
    "link": "PolyDataNormals.html"
  },
  {
    "title": "ThresholdPoints",
    "category": "Filters",
    "image": "gallery/ThresholdPoints.jpg",
    "link": "ThresholdPoints.html"
  },
  {
    "title": "BFSConnectivityFilter",
    "category": "Filters",
    "image": "gallery/BFSConnectivityFilter.png",
    "link": "BFSConnectivityFilter.html"
  },
  {
    "title": "ReverseSense",
    "category": "Filters",
    "image": "gallery/ReverseSense.jpg",
    "link": "ReverseSense.html"
  },
  {
    "title": "Calculator",
    "category": "Filters",
    "image": "gallery/Calculator.jpg",
    "link": "Calculator.html"
  },
  {
    "title": "ContourTriangulator",
    "category": "Filters",
    "image": "gallery/ContourTriangulator.jpg",
    "link": "ContourTriangulator.html"
  },
  {
    "title": "ContourLoopExtraction",
    "category": "Filters",
    "image": "gallery/ContourLoopExtraction.jpg",
    "link": "ContourLoopExtraction.html"
  },
  {
    "title": "ClipClosedSurface",
    "category": "Filters",
    "image": "gallery/ClipClosedSurface.jpg",
    "link": "ClipClosedSurface.html"
  },
  {
    "title": "ImageCropFilter",
    "category": "Filters",
    "image": "gallery/ImageCropFilter.jpg",
    "link": "ImageCropFilter.html"
  },
  {
    "title": "ImageMarchingCubes",
    "category": "Filters",
    "image": "gallery/ImageMarchingCubes.jpg",
    "link": "ImageMarchingCubes.html"
  },
  {
    "title": "ImageMarchingSquares",
    "category": "Filters",
    "image": "gallery/ImageMarchingSquares.jpg",
    "link": "ImageMarchingSquares.html"
  },
  {
    "title": "ImageOutlineFilter",
    "category": "Filters",
    "image": "gallery/ImageOutlineFilter.png",
    "link": "ImageOutlineFilter.html"
  },
  {
    "title": "ImageStreamline",
    "category": "Filters",
    "image": "gallery/ImageStreamline.jpg",
    "link": "ImageStreamline.html"
  },
  {
    "title": "OBBTree",
    "category": "Filters",
    "image": "gallery/OBBTree.jpg",
    "link": "OBBTree.html"
  },
  {
    "title": "OutlineFilter",
    "category": "Filters",
    "image": "gallery/OutlineFilter.jpg",
    "link": "OutlineFilter.html"
  },
  {
    "title": "TriangleFilter",
    "category": "Filters",
    "image": "gallery/TriangleFilter.jpg",
    "link": "TriangleFilter.html"
  },
  {
    "title": "ShrinkPolyData",
    "category": "Filters",
    "image": "gallery/ShrinkPolyData.jpg",
    "link": "ShrinkPolyData.html"
  },
  {
    "title": "WindowedSincPolyDataFilter",
    "category": "Filters",
    "image": "gallery/WindowedSincPolyDataFilter.gif",
    "link": "WindowedSincPolyDataFilter.html"
  },
  {
    "title": "ScalarToRGBA",
    "category": "Filters",
    "image": "gallery/ScalarToRGBA.jpg",
    "link": "ScalarToRGBA.html"
  },
  {
    "title": "TubeFilter",
    "category": "Filters",
    "image": "gallery/TubeFilter.jpg",
    "link": "TubeFilter.html"
  },
  {
    "title": "WarpScalar",
    "category": "Filters",
    "image": "gallery/WarpScalar.jpg",
    "link": "WarpScalar.html"
  },
  {
    "title": "ArcSource",
    "category": "Filters",
    "image": "gallery/ArcSource.jpg",
    "link": "ArcSource.html"
  },
  {
    "title": "FillHolesFilter",
    "category": "Filters",
    "image": "gallery/FillHolesFilter.jpg",
    "link": "FillHolesFilter.html"
  },
  {
    "title": "RibbonFilter",
    "category": "Filters",
    "image": "gallery/RibbonFilter.jpg",
    "link": "RibbonFilter.html"
  },
  {
    "title": "ArrowSource",
    "category": "Filters",
    "image": "gallery/ArrowSource.jpg",
    "link": "ArrowSource.html"
  },
  {
    "title": "ConeSource",
    "category": "Filters",
    "image": "gallery/ConeSource.jpg",
    "link": "ConeSource.html"
  },
  {
    "title": "CircleSource",
    "category": "Filters",
    "image": "gallery/CircleSource.jpg",
    "link": "CircleSource.html"
  },
  {
    "title": "ConcentricCylinderSource",
    "category": "Filters",
    "image": "gallery/ConcentricCylinderSource.jpg",
    "link": "ConcentricCylinderSource.html"
  },
  {
    "title": "CubeSource",
    "category": "Filters",
    "image": "gallery/CubeSource.jpg",
    "link": "CubeSource.html"
  },
  {
    "title": "Cursor3D",
    "category": "Filters",
    "image": "gallery/Cursor3D.gif",
    "link": "Cursor3D.html"
  },
  {
    "title": "FrustumSource",
    "category": "Filters",
    "image": "gallery/FrustumSource.jpg",
    "link": "FrustumSource.html"
  },
  {
    "title": "CylinderSource",
    "category": "Filters",
    "image": "gallery/CylinderSource.jpg",
    "link": "CylinderSource.html"
  },
  {
    "title": "DiskSource",
    "category": "Filters",
    "image": "gallery/DiskSource.png",
    "link": "DiskSource.html"
  },
  {
    "title": "EllipseArcSource",
    "category": "Filters",
    "image": "gallery/EllipseArcSource.jpg",
    "link": "EllipseArcSource.html"
  },
  {
    "title": "PlaneSource",
    "category": "Filters",
    "image": "gallery/PlaneSource.jpg",
    "link": "PlaneSource.html"
  },
  {
    "title": "PlatonicSolidSource",
    "category": "Filters",
    "image": "gallery/PlatonicSolidSource.jpg",
    "link": "PlatonicSolidSource.html"
  },
  {
    "title": "PointSource",
    "category": "Filters",
    "image": "gallery/PointSource.jpg",
    "link": "PointSource.html"
  },
  {
    "title": "LineSource",
    "category": "Filters",
    "image": "gallery/LineSource.jpg",
    "link": "LineSource.html"
  },
  {
    "title": "RegularPolygonSource",
    "category": "Filters",
    "image": "gallery/RegularPolygonSource.jpg",
    "link": "RegularPolygonSource.html"
  },
  {
    "title": "SphereSource",
    "category": "Filters",
    "image": "gallery/SphereSource.gif",
    "link": "SphereSource.html"
  },
  {
    "title": "SLICSource",
    "category": "Filters",
    "image": "gallery/SLICSource.jpg",
    "link": "SLICSource.html"
  },
  {
    "title": "MouseBoxSelectorManipulator",
    "category": "Interaction",
    "image": "gallery/MouseBoxSelectorManipulator.png",
    "link": "MouseBoxSelectorManipulator.html"
  },
  {
    "title": "KeyboardCameraManipulator",
    "category": "Interaction",
    "image": "gallery/KeyboardCameraManipulator.jpg",
    "link": "KeyboardCameraManipulator.html"
  },
  {
    "title": "MouseCameraTrackballFirstPersonManipulator",
    "category": "Interaction",
    "image": "gallery/MouseCameraTrackballFirstPersonManipulator.png",
    "link": "MouseCameraTrackballFirstPersonManipulator.html"
  },
  {
    "title": "MouseRangeManipulator",
    "category": "Interaction",
    "image": "gallery/MouseRangeManipulator.jpg",
    "link": "MouseRangeManipulator.html"
  },
  {
    "title": "TimeStepBasedAnimationHandler",
    "category": "Interaction",
    "image": "gallery/TimeStepBasedAnimationHandler.gif",
    "link": "TimeStepBasedAnimationHandler.html"
  },
  {
    "title": "InteractorStyleManipulatorRotateCameraCenter",
    "category": "Interaction",
    "image": "gallery/InteractorStyleManipulatorRotateCameraCenter.png",
    "link": "InteractorStyleManipulatorRotateCameraCenter.html"
  },
  {
    "title": "InteractorStyleManipulator",
    "category": "Interaction",
    "image": "gallery/InteractorStyleManipulator.jpg",
    "link": "InteractorStyleManipulator.html"
  },
  {
    "title": "InteractorStyleMPRSlice",
    "category": "Interaction",
    "image": "gallery/no-preview.png",
    "link": "InteractorStyleMPRSlice.html"
  },
  {
    "title": "InteractorStyleUnicam",
    "category": "Interaction",
    "image": "gallery/InteractorStyleUnicam.jpg",
    "link": "InteractorStyleUnicam.html"
  },
  {
    "title": "OrientationMarkerWidget",
    "category": "Interaction",
    "image": "gallery/OrientationMarkerWidget.png",
    "link": "OrientationMarkerWidget.html"
  },
  {
    "title": "InteractorStyleTrackballCamera",
    "category": "Interaction",
    "image": "gallery/InteractorStyleTrackballCamera.jpg",
    "link": "InteractorStyleTrackballCamera.html"
  },
  {
    "title": "PiecewiseGaussianWidget",
    "category": "Interaction",
    "image": "gallery/PiecewiseGaussianWidget.jpg",
    "link": "PiecewiseGaussianWidget.html"
  },
  {
    "title": "InteractorStyleHMDXR",
    "category": "Interaction",
    "image": "gallery/InteractorStyleHMDXR.jpg",
    "link": "InteractorStyleHMDXR.html"
  },
  {
    "title": "DeviceOrientationToCamera",
    "category": "Interaction",
    "image": "gallery/DeviceOrientationToCamera.jpg",
    "link": "DeviceOrientationToCamera.html"
  },
  {
    "title": "DracoReader",
    "category": "IO",
    "image": "gallery/DracoReaderWithIcon.jpg",
    "link": "DracoReader.html"
  },
  {
    "title": "GLTFImporter",
    "category": "IO",
    "image": "gallery/GLTFImporterWithIcon.jpg",
    "link": "GLTFImporter.html"
  },
  {
    "title": "IFCImporter",
    "category": "IO",
    "image": "gallery/IFCImporterWithIcon.jpg",
    "link": "IFCImporter.html"
  },
  {
    "title": "PLYWriter",
    "category": "IO",
    "image": "gallery/PLYWriterWithIcon.jpg",
    "link": "PLYWriter.html"
  },
  {
    "title": "STLReader",
    "category": "IO",
    "image": "gallery/STLReaderWithIcon.jpg",
    "link": "STLReader.html"
  },
  {
    "title": "STLWriter",
    "category": "IO",
    "image": "gallery/STLWriterWithIcon.jpg",
    "link": "STLWriter.html"
  },
  {
    "title": "PLYReader",
    "category": "IO",
    "image": "gallery/PLYReaderWithIcon.jpg",
    "link": "PLYReader.html"
  },
  {
    "title": "HDRReader",
    "category": "IO",
    "image": "gallery/HDRReaderWithIcon.jpg",
    "link": "HDRReader.html"
  },
  {
    "title": "TIFFReader",
    "category": "IO",
    "image": "gallery/TIFFReaderWithIcon.jpg",
    "link": "TIFFReader.html"
  },
  {
    "title": "TGAReader",
    "category": "IO",
    "image": "gallery/TGAReaderWithIcon.jpg",
    "link": "TGAReader.html"
  },
  {
    "title": "HttpDataSetReader",
    "category": "IO",
    "image": "gallery/HttpDataSetReaderWithIcon.jpg",
    "link": "HttpDataSetReader.html"
  },
  {
    "title": "ImageStream",
    "category": "IO",
    "image": "gallery/ImageStream.png",
    "link": "ImageStream.html"
  },
  {
    "title": "HttpSceneLoader",
    "category": "IO",
    "image": "gallery/HttpSceneLoader.jpg",
    "link": "HttpSceneLoader.html"
  },
  {
    "title": "HttpDataSetSeriesReader",
    "category": "IO",
    "image": "gallery/HttpDataSetSeriesReaderWithIcon.gif",
    "link": "HttpDataSetSeriesReader.html"
  },
  {
    "title": "ElevationReader",
    "category": "IO",
    "image": "gallery/ElevationReader.jpg",
    "link": "ElevationReader.html"
  },
  {
    "title": "GCodeReader",
    "category": "IO",
    "image": "gallery/GCodeReaderWithIcon.jpg",
    "link": "GCodeReader.html"
  },
  {
    "title": "OBJReader",
    "category": "IO",
    "image": "gallery/OBJReader.jpg",
    "link": "OBJReader.html"
  },
  {
    "title": "JSONNucleoReader",
    "category": "IO",
    "image": "gallery/no-preview.png",
    "link": "JSONNucleoReader.html"
  },
  {
    "title": "PDBReader",
    "category": "IO",
    "image": "gallery/PDBReader.jpg",
    "link": "PDBReader.html"
  },
  {
    "title": "OBJWriter",
    "category": "IO",
    "image": "gallery/OBJWriterWithIcon.jpg",
    "link": "OBJWriter.html"
  },
  {
    "title": "XMLImageDataWriter",
    "category": "IO",
    "image": "gallery/XMLImageDataWriterWithIcon.jpg",
    "link": "XMLImageDataWriter.html"
  },
  {
    "title": "PolyDataReader",
    "category": "IO",
    "image": "gallery/PolyDataReaderWithIcon.jpg",
    "link": "PolyDataReader.html"
  },
  {
    "title": "WidgetManager",
    "category": "Widgets",
    "image": "gallery/WidgetManager.png",
    "link": "WidgetManager.html"
  },
  {
    "title": "XMLPolyDataWriter",
    "category": "IO",
    "image": "gallery/XMLPolyDataWriterWithIcon.jpg",
    "link": "XMLPolyDataWriter.html"
  },
  {
    "title": "ProxyManager",
    "category": "Proxy",
    "image": "gallery/no-preview.png",
    "link": "ProxyManager.html"
  },
  {
    "title": "View2DProxy",
    "category": "Proxy",
    "image": "gallery/no-preview.png",
    "link": "View2DProxy.html"
  },
  {
    "title": "AnimationProxyManager",
    "category": "Proxy",
    "image": "gallery/AnimationProxyManager.png",
    "link": "AnimationProxyManager.html"
  },
  {
    "title": "ResliceRepresentationProxy",
    "category": "Proxy",
    "image": "gallery/no-preview.png",
    "link": "ResliceRepresentationProxy.html"
  },
  {
    "title": "AngleWidget",
    "category": "Widgets",
    "image": "gallery/AngleWidget.png",
    "link": "AngleWidget.html"
  },
  {
    "title": "ImplicitPlaneWidget",
    "category": "Widgets",
    "image": "gallery/ImplicitPlaneWidget.png",
    "link": "ImplicitPlaneWidget.html"
  },
  {
    "title": "ImageCroppingWidget",
    "category": "Widgets",
    "image": "gallery/ImageCroppingWidget.jpg",
    "link": "ImageCroppingWidget.html"
  },
  {
    "title": "LineWidget",
    "category": "Widgets",
    "image": "gallery/LineWidget.png",
    "link": "LineWidget.html"
  },
  {
    "title": "InteractiveOrientationWidget",
    "category": "Widgets",
    "image": "gallery/InteractiveOrientationWidget.png",
    "link": "InteractiveOrientationWidget.html"
  },
  {
    "title": "LabelWidget",
    "category": "Widgets",
    "image": "gallery/LabelWidget.png",
    "link": "LabelWidget.html"
  },
  {
    "title": "PolyLineWidget",
    "category": "Widgets",
    "image": "gallery/PolyLineWidget.png",
    "link": "PolyLineWidget.html"
  },
  {
    "title": "SeedWidget",
    "category": "Widgets",
    "image": "gallery/SeedWidget.png",
    "link": "SeedWidget.html"
  },
  {
    "title": "ShapeWidget",
    "category": "Widgets",
    "image": "gallery/ShapeWidget.png",
    "link": "ShapeWidget.html"
  },
  {
    "title": "PaintWidget",
    "category": "Widgets",
    "image": "gallery/PaintWidget.gif",
    "link": "PaintWidget.html"
  },
  {
    "title": "SphereWidget",
    "category": "Widgets",
    "image": "gallery/SphereWidget.jpg",
    "link": "SphereWidget.html"
  },
  {
    "title": "SplineWidget",
    "category": "Widgets",
    "image": "gallery/SplineWidget.gif",
    "link": "SplineWidget.html"
  },
  {
    "title": "TransformControlsWidget",
    "category": "Widgets",
    "image": "gallery/TransformControlsWidget.png",
    "link": "TransformControlsWidget.html"
  },
  {
    "title": "ResliceCursorWidget",
    "category": "Widgets",
    "image": "gallery/ResliceCursorWidget.jpg",
    "link": "ResliceCursorWidget.html"
  },
  {
    "title": "ImplicitPlaneRepresentation",
    "category": "Widgets",
    "image": "gallery/ImplicitPlaneRepresentation.png",
    "link": "ImplicitPlaneRepresentation.html"
  },
  {
    "title": "WidgetRepresentation",
    "category": "Widgets",
    "image": "gallery/WidgetRepresentation.png",
    "link": "WidgetRepresentation.html"
  },
  {
    "title": "CellPicker",
    "category": "Rendering",
    "image": "gallery/CellPicker.jpg",
    "link": "CellPicker.html"
  },
  {
    "title": "CutterMapper",
    "category": "Rendering",
    "image": "gallery/CutterMapper.jpg",
    "link": "CutterMapper.html"
  },
  {
    "title": "Glyph3DMapper",
    "category": "Rendering",
    "image": "gallery/Glyph3DMapper.jpg",
    "link": "Glyph3DMapper.html"
  },
  {
    "title": "ImageMapper",
    "category": "Rendering",
    "image": "gallery/ImageMapper.jpg",
    "link": "ImageMapper.html"
  },
  {
    "title": "HardwareSelector",
    "category": "Rendering",
    "image": "gallery/HardwareSelector.jpg",
    "link": "HardwareSelector.html"
  },
  {
    "title": "ImageCPRMapper",
    "category": "Rendering",
    "image": "gallery/ImageCPRMapper.jpg",
    "link": "ImageCPRMapper.html"
  },
  {
    "title": "ImageResliceMapper",
    "category": "Rendering",
    "image": "gallery/ImageResliceMapper.gif",
    "link": "ImageResliceMapper.html"
  },
  {
    "title": "PointPicker",
    "category": "Rendering",
    "image": "gallery/PointPicker.jpg",
    "link": "PointPicker.html"
  },
  {
    "title": "SphereMapper",
    "category": "Rendering",
    "image": "gallery/SphereMapper.jpg",
    "link": "SphereMapper.html"
  },
  {
    "title": "StickMapper",
    "category": "Rendering",
    "image": "gallery/StickMapper.jpg",
    "link": "StickMapper.html"
  },
  {
    "title": "TextActor",
    "category": "Rendering",
    "image": "gallery/TextActor.jpg",
    "link": "TextActor.html"
  },
  {
    "title": "VectorText",
    "category": "Rendering",
    "image": "gallery/VectorText.jpg",
    "link": "VectorText.html"
  },
  {
    "title": "VolumeMapper",
    "category": "Rendering",
    "image": "gallery/VolumeMapper.jpg",
    "link": "VolumeMapper.html"
  },
  {
    "title": "ScalarBarActor",
    "category": "Rendering",
    "image": "gallery/ScalarBarActor.jpg",
    "link": "ScalarBarActor.html"
  },
  {
    "title": "RemoteView",
    "category": "Rendering",
    "image": "gallery/no-preview.png",
    "link": "RemoteView.html"
  },
  {
    "title": "SynchronizableRenderWindow",
    "category": "Rendering",
    "image": "gallery/no-preview.png",
    "link": "SynchronizableRenderWindow.html"
  },
  {
    "title": "RenderWindowWithControlBar",
    "category": "Rendering",
    "image": "gallery/RenderWindowWithControlBar.png",
    "link": "RenderWindowWithControlBar.html"
  },
  {
    "title": "SurfaceLICMapper",
    "category": "Rendering",
    "image": "gallery/SurfaceLICMapper.jpg",
    "link": "SurfaceLICMapper.html"
  },
  {
    "title": "ImageViewer",
    "category": "Applications",
    "image": "gallery/no-preview.png",
    "link": "ImageViewer.html"
  },
  {
    "title": "GeometryViewer",
    "category": "Applications",
    "image": "gallery/GeometryViewer.jpg",
    "link": "GeometryViewer.html"
  },
  {
    "title": "OctreeViewer",
    "category": "Applications",
    "image": "gallery/no-preview.png",
    "link": "OctreeViewer.html"
  },
  {
    "title": "OBJViewer",
    "category": "Applications",
    "image": "gallery/OBJViewer.png",
    "link": "OBJViewer.html"
  },
  {
    "title": "SceneExplorer",
    "category": "Applications",
    "image": "gallery/SceneExplorer.png",
    "link": "SceneExplorer.html"
  },
  {
    "title": "OfflineLocalView",
    "category": "Applications",
    "image": "gallery/OfflineLocalViewWithIcon.jpg",
    "link": "OfflineLocalView.html"
  },
  {
    "title": "TubesViewer",
    "category": "Applications",
    "image": "gallery/no-preview.png",
    "link": "TubesViewer.html"
  },
  {
    "title": "SkyboxViewer",
    "category": "Applications",
    "image": "gallery/SkyboxViewer.jpg",
    "link": "SkyboxViewer.html"
  },
  {
    "title": "VolumeViewer",
    "category": "Applications",
    "image": "gallery/VolumeViewer.jpg",
    "link": "VolumeViewer.html"
  },
  {
    "title": "AR",
    "category": "Geometry",
    "image": "gallery/no-preview.png",
    "link": "AR.html"
  },
  {
    "title": "AxesActor",
    "category": "Geometry",
    "image": "gallery/AxesActor.png",
    "link": "AxesActor.html"
  },
  {
    "title": "Cone",
    "category": "Geometry",
    "image": "gallery/Cone.jpg",
    "link": "Cone.html"
  },
  {
    "title": "CubeAxes",
    "category": "Geometry",
    "image": "gallery/CubeAxes.jpg",
    "link": "CubeAxes.html"
  },
  {
    "title": "DepthTest",
    "category": "Geometry",
    "image": "gallery/DepthTest.jpg",
    "link": "DepthTest.html"
  },
  {
    "title": "GlyphRotation",
    "category": "Geometry",
    "image": "gallery/GlyphRotation.jpg",
    "link": "GlyphRotation.html"
  },
  {
    "title": "LookingGlass",
    "category": "Geometry",
    "image": "gallery/no-preview.png",
    "link": "LookingGlass.html"
  },
  {
    "title": "Picking",
    "category": "Geometry",
    "image": "gallery/Picking.png",
    "link": "Picking.html"
  },
  {
    "title": "ItkWasmGeometry",
    "category": "Geometry",
    "image": "gallery/no-preview.png",
    "link": "ItkWasmGeometry.html"
  },
  {
    "title": "Texture",
    "category": "Geometry",
    "image": "gallery/Texture.jpg",
    "link": "Texture.html"
  },
  {
    "title": "SpheresAndLabels",
    "category": "Geometry",
    "image": "gallery/SpheresAndLabels.jpg",
    "link": "SpheresAndLabels.html"
  },
  {
    "title": "SimpleCone",
    "category": "Geometry",
    "image": "gallery/SimpleCone.png",
    "link": "SimpleCone.html"
  },
  {
    "title": "TimeSeries",
    "category": "Geometry",
    "image": "gallery/TimeSeries.gif",
    "link": "TimeSeries.html"
  },
  {
    "title": "VR",
    "category": "Geometry",
    "image": "gallery/no-preview.png",
    "link": "VR.html"
  },
  {
    "title": "Actor2D",
    "category": "Rendering",
    "image": "gallery/Actor2D.jpg",
    "link": "Actor2D.html"
  },
  {
    "title": "CustomWebGPUCone",
    "category": "Rendering",
    "image": "gallery/no-preview.png",
    "link": "CustomWebGPUCone.html"
  },
  {
    "title": "ImageResliceMapperLabelOutline",
    "category": "Rendering",
    "image": "gallery/ImageResliceMapperLabelOutline.jpg",
    "link": "ImageResliceMapperLabelOutline.html"
  },
  {
    "title": "KeyPressEvents",
    "category": "Rendering",
    "image": "gallery/KeyPressEvents.png",
    "link": "KeyPressEvents.html"
  },
  {
    "title": "Convolution2DPass",
    "category": "Rendering",
    "image": "gallery/Convolution2DPass.gif",
    "link": "Convolution2DPass.html"
  },
  {
    "title": "ImageLabelOutline",
    "category": "Rendering",
    "image": "gallery/ImageLabelOutline.jpg",
    "link": "ImageLabelOutline.html"
  },
  {
    "title": "LabelmapEdgeProjection",
    "category": "Rendering",
    "image": "gallery/LabelmapEdgeProjection.gif",
    "link": "LabelmapEdgeProjection.html"
  },
  {
    "title": "ManyRenderWindows",
    "category": "Rendering",
    "image": "gallery/ManyRenderWindows.jpg",
    "link": "ManyRenderWindows.html"
  },
  {
    "title": "LabelmapEdgeProjectionReslice",
    "category": "Rendering",
    "image": "gallery/LabelmapEdgeProjectionReslice.png",
    "link": "LabelmapEdgeProjectionReslice.html"
  },
  {
    "title": "MouseEvents",
    "category": "Rendering",
    "image": "gallery/MouseEvents.jpg",
    "link": "MouseEvents.html"
  },
  {
    "title": "ManyRenderers",
    "category": "Rendering",
    "image": "gallery/ManyRenderers.gif",
    "link": "ManyRenderers.html"
  },
  {
    "title": "QuadView",
    "category": "Rendering",
    "image": "gallery/QuadView.jpg",
    "link": "QuadView.html"
  },
  {
    "title": "PBR",
    "category": "Rendering",
    "image": "gallery/no-preview.png",
    "link": "PBR.html"
  },
  {
    "title": "SphereArray",
    "category": "Rendering",
    "image": "gallery/SphereArray.jpg",
    "link": "SphereArray.html"
  },
  {
    "title": "MultiSliceImageMapper",
    "category": "Volume",
    "image": "gallery/MultiSliceImageMapper.jpg",
    "link": "MultiSliceImageMapper.html"
  },
  {
    "title": "ItkWasmVolume",
    "category": "Volume",
    "image": "gallery/ItkWasmVolume.jpg",
    "link": "ItkWasmVolume.html"
  },
  {
    "title": "Scrolling2DMixedImages",
    "category": "Volume",
    "image": "gallery/no-preview.png",
    "link": "Scrolling2DMixedImages.html"
  },
  {
    "title": "TestVolumeTypes",
    "category": "Volume",
    "image": "gallery/TestVolumeTypes.jpg",
    "link": "TestVolumeTypes.html"
  },
  {
    "title": "VolumeClipPlane",
    "category": "Volume",
    "image": "gallery/VolumeClipPlane.jpg",
    "link": "VolumeClipPlane.html"
  },
  {
    "title": "VolumeContour",
    "category": "Volume",
    "image": "gallery/VolumeContour.jpg",
    "link": "VolumeContour.html"
  },
  {
    "title": "VolumeMapperParallelProjection",
    "category": "Volume",
    "image": "gallery/VolumeMapperParallelProjection.jpg",
    "link": "VolumeMapperParallelProjection.html"
  },
  {
    "title": "VolumeOutline",
    "category": "Volume",
    "image": "gallery/VolumeOutline.jpg",
    "link": "VolumeOutline.html"
  },
  {
    "title": "VolumeMapperBlendModes",
    "category": "Volume",
    "image": "gallery/VolumeMapperBlendModes.gif",
    "link": "VolumeMapperBlendModes.html"
  },
  {
    "title": "VolumePicker",
    "category": "Volume",
    "image": "gallery/VolumePicker.png",
    "link": "VolumePicker.html"
  },
  {
    "title": "VolumeRenderingWithPolyData",
    "category": "Volume",
    "image": "gallery/VolumeRenderingWithPolyData.jpg",
    "link": "VolumeRenderingWithPolyData.html"
  },
  {
    "title": "WebXRChestCTBlendedCVR",
    "category": "Volume",
    "image": "gallery/no-preview.png",
    "link": "WebXRChestCTBlendedCVR.html"
  },
  {
    "title": "WebXRHeadFullVolumeCVR",
    "category": "Volume",
    "image": "gallery/no-preview.png",
    "link": "WebXRHeadFullVolumeCVR.html"
  },
  {
    "title": "WebXRHeadGradientCVR",
    "category": "Volume",
    "image": "gallery/no-preview.png",
    "link": "WebXRHeadGradientCVR.html"
  },
  {
    "title": "WebXRVolume",
    "category": "Volume",
    "image": "gallery/WebXRVolume.png",
    "link": "WebXRVolume.html"
  },
  {
    "title": "VolumeMapperLightAndShadow",
    "category": "Volume",
    "image": "gallery/VolumeMapperLightAndShadow.jpg",
    "link": "VolumeMapperLightAndShadow.html"
  },
  {
    "title": "ZipHttpReader",
    "category": "Volume",
    "image": "gallery/ZipHttpReader.jpg",
    "link": "ZipHttpReader.html"
  },
  {
    "title": "ResliceCursorWidgetLabelmap",
    "category": "Widgets",
    "image": "gallery/ResliceCursorWidgetLabelmap.jpg",
    "link": "ResliceCursorWidgetLabelmap.html"
  },
  {
    "title": "Box",
    "category": "Widgets",
    "image": "gallery/Box.jpg",
    "link": "Box.html"
  },
  {
    "title": "ImageInterpolator",
    "category": "Rendering",
    "image": "gallery/ImageInterpolator.jpg",
    "link": "ImageInterpolator.html"
  }
];
