export const COLOR_MODE = [
  'VTK_COLOR_MODE_DEFAULT',
  'VTK_COLOR_MODE_MAP_SCALARS',
  'VTK_COLOR_MODE_DIRECT_SCALARS',
];

export const SCALAR_MODE = [
  'VTK_SCALAR_MODE_DEFAULT',
  'VTK_SCALAR_MODE_USE_POINT_DATA',
  'VTK_SCALAR_MODE_USE_CELL_DATA',
  'VTK_SCALAR_MODE_USE_POINT_FIELD_DATA',
  'VTK_SCALAR_MODE_USE_CELL_FIELD_DATA',
  'VTK_SCALAR_MODE_USE_FIELD_DATA',
];

export const MATERIAL_MODE = [
  'VTK_MATERIALMODE_DEFAULT',
  'VTK_MATERIALMODE_AMBIENT',
  'VTK_MATERIALMODE_DIFFUSE',
  'VTK_MATERIALMODE_AMBIENT_AND_DIFFUSE',
];

export const MATERIAL_MODE_VALUES = {
  VTK_MATERIALMODE_DEFAULT: 0,
  VTK_MATERIALMODE_AMBIENT: 1,
  VTK_MATERIALMODE_DIFFUSE: 2,
  VTK_MATERIALMODE_AMBIENT_AND_DIFFUSE: 3,
};

export default { MATERIAL_MODE_VALUES };
