export const VTK_COLOR_MODE = {
  DEFAULT: 0,
  MAP_SCALARS: 1,
  DIRECT_SCALARS: 2,
};

export const VTK_SCALAR_MODE = {
  DEFAULT: 0,
  USE_POINT_DATA: 1,
  USE_CELL_DATA: 2,
  USE_POINT_FIELD_DATA: 3,
  USE_CELL_FIELD_DATA: 4,
  USE_FIELD_DATA: 5,
};

export const VTK_MATERIALMODE = {
  DEFAULT: 0,
  AMBIENT: 1,
  DIFFUSE: 2,
  AMBIENT_AND_DIFFUSE: 3,
};

export const VTK_GET_ARRAY = {
  BY_ID: 0,
  BY_NAME: 1,
};

export default { VTK_COLOR_MODE, VTK_MATERIALMODE, VTK_GET_ARRAY, VTK_SCALAR_MODE };
