name: Feature Request
description: Suggest an idea for vtk.js.
title: '[Feature] '
labels: 'type: feature request 💡'
body:
  - type: markdown
    attributes:
      value: |
        👋 Hello, and thank you for starting this contribution!

        ❓ If you are trying to submit a question for general support, please reach out on our discourse forum instead: https://discourse.vtk.org/c/web/9

        🐞 If you do need to report a bug, please complete the template below as much as possible to help us reproduce the bug and address your report.

        🧱 When appropriate, assign one of the `Module: XXX` labels to your issue when creating it.
  - type: textarea
    id: description
    attributes:
      label: Feature Request
      description: A clear and concise description of what need or problem you're trying to address.
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Motivation and Detailed Description
      description: |
        A clear description of the feature/enhancement you'd like to see being added.
        If applicable, use:

        - potential alternatives
        - screenshots
    validations:
      required: true
