export const STATES = {
  VTKIS_START: 0,
  VTKIS_NONE: 0,

  VTKIS_ROTATE: 1,
  VTKIS_PAN: 2,
  VTKIS_SPIN: 3,
  VTKIS_DOLLY: 4,
  VTKIS_ZOOM: 5,
  VTKIS_USCALE: 6,
  VTKIS_TIMER: 7,
  VTKIS_FORWARDFLY: 8,
  VTKIS_REVERSEFLY: 9,
  VTKIS_TWO_POINTER: 10,

  VTKIS_ANIM_OFF: 0,
  VTKIS_ANIM_ON: 1,

  VTKIS_WINDOW_LEVEL: 1024,
  VTKIS_PICK: 1025,
  VTKIS_SLICE: 1026,
};

export default {
  STATES,
};
