// This script generates examples-list.js for the docs examples gallery
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Adjust these paths as needed
const SOURCES_ROOT = path.resolve(__dirname, '../../Sources/');
const EXAMPLES_ROOT = path.resolve(__dirname, '../../Examples/');
const OUTPUT_FILE = path.join(__dirname, '../examples/gallery.js');

const EXAMPLE_SOURCES = [
  {
    root: SOURCES_ROOT,
    shouldSkipDir: (relDir) =>
      relDir === 'Testing' || relDir.startsWith('Testing/'),
    isExampleFile: (relPath) => /\/example\/index\.js$/.test(relPath),
    getExampleName: (fullPath) =>
      path.basename(path.dirname(path.dirname(fullPath))),
  },
  {
    root: EXAMPLES_ROOT,
    shouldSkipDir: () => false,
    isExampleFile: (relPath) => {
      const segments = relPath.split('/');
      return segments.length === 3 && segments[2] === 'index.js';
    },
    getExampleName: (fullPath) => path.basename(path.dirname(fullPath)),
  },
];

async function hasScreenshot(screenshotPath) {
  try {
    await fs.access(screenshotPath);
    return true;
  } catch (e) {
    return false;
  }
}

async function walkExamples(
  config,
  dir = config.root,
  category = null,
  results = []
) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  await Promise.all(
    entries.map(async (entry) => {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        const relDir = path.relative(config.root, fullPath).replace(/\\/g, '/');
        if (relDir && config.shouldSkipDir(relDir)) {
          return;
        }
        await walkExamples(config, fullPath, category || entry.name, results);
      } else if (entry.name === 'index.js') {
        // Only include if path matches /example/index.js$/
        const relPath = path
          .relative(config.root, fullPath)
          .replace(/\\/g, '/');
        if (!config.isExampleFile(relPath)) return;
        const exampleName = config.getExampleName(fullPath, relPath);
        const exampleCategory = category || 'Uncategorized';
        const galleryDir = path.resolve(__dirname, '../public/gallery');
        let image = null;
        const exts = ['png', 'jpg', 'gif'];
        const candidates = exts.flatMap((ext) => [
          `gallery/${exampleName}.${ext}`,
          `gallery/${exampleName}WithIcon.${ext}`,
        ]);
        // Check all candidates in parallel
        const existsArr = await Promise.all(
          candidates.map((imgPath) => {
            const absPath = path.join(
              galleryDir,
              imgPath.replace('gallery', '')
            );
            console.log('Checking for screenshot:', absPath);
            return hasScreenshot(absPath);
          })
        );
        const foundIdx = existsArr.findIndex(Boolean);
        if (foundIdx !== -1) {
          image = candidates[foundIdx];
        } else {
          image = 'gallery/no-preview.png';
        }
        // Link convention
        const link = `${exampleName}.html`;
        results.push({
          title: exampleName,
          category: exampleCategory,
          image,
          link,
        });
      }
    })
  );
  return results;
}

async function main() {
  const examplesByRoot = await Promise.all(
    EXAMPLE_SOURCES.map((config) => walkExamples(config))
  );
  const examples = examplesByRoot.flat();
  const content =
    `// This file is auto-generated by generate-gallery.mjs\n` +
    `export default ${JSON.stringify(examples, null, 2)};\n`;
  await fs.writeFile(OUTPUT_FILE, content);
  console.log(`Generated ${OUTPUT_FILE} with ${examples.length} examples.`);
}

main();
