name: PR Checks
on: pull_request

jobs:
  pr-checks:
    runs-on: ubuntu-20.04
    name: Check and lint PR
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # needed so commitlint can lint the commits
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Enforce code style
        run: npm run validate
      - name: Lint commits
        run: npx commitlint --from=${{ github.event.pull_request.base.sha }}
      - name: Tests must not use test.only
        run: bash .github/workflows/test-only-check.sh
